from __future__ import annotations

import json
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DEFAULT_DART_ROOT = Path(".cache/upstreams/dart-gui")
DEFAULT_DART_RUN_ROOT = Path(".w8-biayn/osworld-dart/runs")
DEFAULT_MODEL = "Qwen/Qwen2.5-VL-7B-Instruct"
DEFAULT_ROLLOUT_SERVER_URL = "http://127.0.0.1:15959"


@dataclass(frozen=True)
class DartRunConfigResult:
    run_id: str
    out_dir: Path
    rollouter_config: Path
    env_file: Path
    trainer_script: Path
    manifest_path: Path
    task_file: Path
    osworld_root: Path
    storage_root: Path
    dart_root: Path

    def as_dict(self) -> dict[str, Any]:
        return {
            "run_id": self.run_id,
            "out_dir": str(self.out_dir),
            "rollouter_config": str(self.rollouter_config),
            "env_file": str(self.env_file),
            "trainer_script": str(self.trainer_script),
            "manifest_path": str(self.manifest_path),
            "task_file": str(self.task_file),
            "osworld_root": str(self.osworld_root),
            "storage_root": str(self.storage_root),
            "dart_root": str(self.dart_root),
        }


def _json_write(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _ensure_clean_out_dir(out_dir: Path, *, force: bool) -> None:
    if out_dir.exists() and any(out_dir.iterdir()) and not force:
        raise FileExistsError(f"output directory is not empty; pass --force to overwrite: {out_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)


def _yaml_bool(value: bool) -> str:
    return "true" if value else "false"


def _yaml_string(value: str | Path) -> str:
    return json.dumps(str(value))


def _shell_export(name: str, value: str | Path | int | float | bool) -> str:
    return f"export {name}={shlex.quote(str(value))}"


def _absolute_path(value: str | Path) -> Path:
    return Path(value).expanduser().resolve(strict=False)


def render_rollouter_config(
    *,
    task_file: Path,
    osworld_root: Path,
    storage_root: Path,
    model: str,
    rollout_server_url: str,
    max_steps: int,
    rollout_n: int,
    max_concurrent_envs: int,
    max_task_queue_size: int,
    screen_width: int,
    screen_height: int,
    headless: bool,
    provider_name: str,
    os_type: str,
    require_a11y_tree: bool,
    write_to_mysql: bool,
) -> str:
    return f"""task:
  task_file: {_yaml_string(task_file)}
  osworld_root: {_yaml_string(osworld_root)}
  resume: false

storage:
  root: {_yaml_string(storage_root)}

model:
  ckpt_path: {_yaml_string(model)}
  replicas: 1
  base_port: 8000
  host: "0.0.0.0"
  service_port: 15959
  service_endpoint: {_yaml_string(rollout_server_url)}
  save_local: true
  vllm_params:
    gpu_memory_utilization: 0.6

coordinator:
  max_concurrent_envs: {max_concurrent_envs}
  max_task_queue_size: {max_task_queue_size}
  rollout_n: {rollout_n}

runner:
  max_steps: {max_steps}
  max_images: 5
  max_texts: 35
  write_to_mysql: {_yaml_bool(write_to_mysql)}
  rollout_n: {rollout_n}
  env:
    max_retries: 3
    action_space: "pyautogui"
    screen_size: [{screen_width}, {screen_height}]
    headless: {_yaml_bool(headless)}
    os_type: {_yaml_string(os_type)}
    require_a11y_tree: {_yaml_bool(require_a11y_tree)}
    provider_name: {_yaml_string(provider_name)}
  model_pool:
    timeout: 100
    retries: 10
    backoff: 2
    frequency_penalty: 1
    temperature: 0.7
    top_p: 1
    max_tokens: 500
    seed: 1
    ckpt_path: {_yaml_string(model)}
    logprobs: true
    return_tokens_as_token_ids: true

mysql:
  username: "dart_rollouter"
  password: "password"
  host: "127.0.0.1"
  port: 3306
  database: "dart_database"
"""


def render_env_file(
    *,
    run_id: str,
    dart_root: Path,
    task_file: Path,
    osworld_root: Path,
    storage_root: Path,
    model: str,
    rollout_server_url: str,
    mlflow_tracking_uri: str | None,
    mlflow_experiment: str | None,
    wandb_project: str | None,
    wandb_run_name: str | None,
) -> str:
    lines = [
        "# Generated by `w8-biayn osworld custom dart config`.",
        "# Source this file before manually running DART commands from the generated run directory.",
        _shell_export("W8_DART_RUN_ID", run_id),
        _shell_export("W8_DART_ROOT", dart_root),
        _shell_export("W8_DART_TASK_FILE", task_file),
        _shell_export("W8_DART_OSWORLD_ROOT", osworld_root),
        _shell_export("W8_DART_STORAGE_ROOT", storage_root),
        _shell_export("MODEL_PATH", model),
        _shell_export("ROLLOUT_SERVER_URL", rollout_server_url),
    ]
    if mlflow_tracking_uri:
        lines.append(_shell_export("MLFLOW_TRACKING_URI", mlflow_tracking_uri))
    if mlflow_experiment:
        lines.append(_shell_export("MLFLOW_EXPERIMENT_NAME", mlflow_experiment))
    if wandb_project:
        lines.append(_shell_export("WANDB_PROJECT", wandb_project))
    if wandb_run_name:
        lines.append(_shell_export("WANDB_RUN_NAME", wandb_run_name))
    return "\n".join(lines) + "\n"


def render_trainer_script(
    *,
    dart_root: Path,
    rollouter_config: Path,
    env_file: Path,
    model: str,
    rollout_server_url: str,
    max_steps: int,
    rollout_n: int,
) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
source "{env_file}"

cd "{dart_root}/dart_rollouter"

echo "DART rollouter config: {rollouter_config}"
echo "Task file: $W8_DART_TASK_FILE"
echo "OSWorld root: $W8_DART_OSWORLD_ROOT"
echo "Storage root: $W8_DART_STORAGE_ROOT"

# Rollout smoke command. This is intentionally rollouter-only; trainer wiring comes after rollout is proven.
PYTHONPATH="$PWD" python3 -m src.run --config-path "$(dirname "{rollouter_config}")" --config-name "$(basename "{rollouter_config}" .yaml)"

# Training command scaffold. Keep disabled until the rollout smoke is confirmed healthy.
cat <<'EOF'
Next DART trainer values:
  MODEL_PATH={model}
  ROLLOUT_SERVER_URL={rollout_server_url}
  rollout_n={rollout_n}
  max_steps={max_steps}
EOF
"""


def write_dart_run_config(
    *,
    run_id: str,
    task_file: str | Path,
    osworld_root: str | Path,
    out_dir: str | Path | None = None,
    dart_root: str | Path = DEFAULT_DART_ROOT,
    storage_root: str | Path | None = None,
    model: str = DEFAULT_MODEL,
    rollout_server_url: str = DEFAULT_ROLLOUT_SERVER_URL,
    max_steps: int = 15,
    rollout_n: int = 1,
    max_concurrent_envs: int = 1,
    max_task_queue_size: int = 1,
    screen_width: int = 1920,
    screen_height: int = 1080,
    headless: bool = True,
    provider_name: str = "docker_server",
    os_type: str = "Ubuntu",
    require_a11y_tree: bool = False,
    write_to_mysql: bool = False,
    mlflow_tracking_uri: str | None = None,
    mlflow_experiment: str | None = None,
    wandb_project: str | None = None,
    wandb_run_name: str | None = None,
    force: bool = False,
) -> DartRunConfigResult:
    if not run_id.strip():
        raise ValueError("run_id must be non-empty")
    if max_steps < 1:
        raise ValueError("max_steps must be >= 1")
    if rollout_n < 1:
        raise ValueError("rollout_n must be >= 1")
    if max_concurrent_envs < 1:
        raise ValueError("max_concurrent_envs must be >= 1")
    if max_task_queue_size < 1:
        raise ValueError("max_task_queue_size must be >= 1")

    clean_run_id = run_id.strip()
    out_path = _absolute_path(out_dir) if out_dir else _absolute_path(DEFAULT_DART_RUN_ROOT / clean_run_id)
    task_path = _absolute_path(task_file)
    root_path = _absolute_path(osworld_root)
    dart_path = _absolute_path(dart_root)
    storage_path = _absolute_path(storage_root) if storage_root else out_path / "rollouts"
    rollouter_config = out_path / "rollouter_config.yaml"
    env_file = out_path / "env.sh"
    trainer_script = out_path / "run_dart_rollout.sh"
    manifest_path = out_path / "manifest.json"

    _ensure_clean_out_dir(out_path, force=force)

    rollouter_config.write_text(
        render_rollouter_config(
            task_file=task_path,
            osworld_root=root_path,
            storage_root=storage_path,
            model=model,
            rollout_server_url=rollout_server_url,
            max_steps=max_steps,
            rollout_n=rollout_n,
            max_concurrent_envs=max_concurrent_envs,
            max_task_queue_size=max_task_queue_size,
            screen_width=screen_width,
            screen_height=screen_height,
            headless=headless,
            provider_name=provider_name,
            os_type=os_type,
            require_a11y_tree=require_a11y_tree,
            write_to_mysql=write_to_mysql,
        ),
        encoding="utf-8",
    )
    env_file.write_text(
        render_env_file(
            run_id=clean_run_id,
            dart_root=dart_path,
            task_file=task_path,
            osworld_root=root_path,
            storage_root=storage_path,
            model=model,
            rollout_server_url=rollout_server_url,
            mlflow_tracking_uri=mlflow_tracking_uri,
            mlflow_experiment=mlflow_experiment,
            wandb_project=wandb_project,
            wandb_run_name=wandb_run_name,
        ),
        encoding="utf-8",
    )
    trainer_script.write_text(
        render_trainer_script(
            dart_root=dart_path,
            rollouter_config=rollouter_config,
            env_file=env_file,
            model=model,
            rollout_server_url=rollout_server_url,
            max_steps=max_steps,
            rollout_n=rollout_n,
        ),
        encoding="utf-8",
    )
    trainer_script.chmod(0o755)
    _json_write(
        manifest_path,
        {
            "schema_version": "w8-osworld-dart-run-config-v1",
            "run_id": clean_run_id,
            "dart_root": str(dart_path),
            "task_file": str(task_path),
            "osworld_root": str(root_path),
            "storage_root": str(storage_path),
            "rollouter_config": str(rollouter_config),
            "env_file": str(env_file),
            "trainer_script": str(trainer_script),
            "model": model,
            "rollout_server_url": rollout_server_url,
            "rollout_n": rollout_n,
            "max_steps": max_steps,
            "max_concurrent_envs": max_concurrent_envs,
            "max_task_queue_size": max_task_queue_size,
            "write_to_mysql": write_to_mysql,
            "tracking": {
                "mlflow_tracking_uri": mlflow_tracking_uri,
                "mlflow_experiment": mlflow_experiment,
                "wandb_project": wandb_project,
                "wandb_run_name": wandb_run_name,
            },
        },
    )

    return DartRunConfigResult(
        run_id=clean_run_id,
        out_dir=out_path,
        rollouter_config=rollouter_config,
        env_file=env_file,
        trainer_script=trainer_script,
        manifest_path=manifest_path,
        task_file=task_path,
        osworld_root=root_path,
        storage_root=storage_path,
        dart_root=dart_path,
    )
